version: '2'
services:
  node-exporter:
    image: prom/node-exporter:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
  prom-conf:
    image: infinityworks/prom-conf:16
    network_mode: none
    volumes:
    - /etc/prom-conf/
    tty: true
    links:
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    - cadvisor:cadvisor
    - node-exporter:node-exporter
  grafana:
    image: grafana/grafana:3.0.1
    tty: true
    links:
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    - prometheus:prometheus
    volumes_from:
    - graf-db
    ports:
    - 3000:3000/tcp
    labels:
      io.rancher.sidekicks: graf-db
  cadvisor:
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
  prometheus-rancher-exporter:
    image: infinityworks/prometheus-rancher-exporter:10
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  prometheus:
    image: prom/prometheus:v1.3.1
    tty: true
    links:
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    volumes_from:
    - prom-conf
    ports:
    - 9090:9090/tcp
    command:
    - -alertmanager.url=http://alertmanager:9093
    - -config.file=/etc/prom-conf/prometheus.yml
    - -storage.local.path=/prometheus
    - -web.console.libraries=/etc/prometheus/console_libraries
    - -web.console.templates=/etc/prometheus/consoles
    labels:
      io.rancher.sidekicks: prom-conf
      io.rancher.scheduler.affinity:host_label: name=front-end
  graf-db:
    image: infinityworks/graf-db:09
    network_mode: none
    volumes:
    - /var/lib/grafana/
    tty: true
    links:
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    - prometheus:prometheus
    command:
    - cat
  influxdb:
    image: tutum/influxdb:0.10
    environment:
      GRAPHITE_BINDING: :2003
      GRAPHITE_DB: rancher
      PRE_CREATE_DB: grafana;prometheus;rancher
    ports:
    - 2003:2003/tcp

