.catalog:
  name: "Blue-Green Cool App"
  version: 3
  description: "A simple blue-green demo app"

version: '2'
services:
  nginx:
    scale: 2
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
