version: '2'
services:
  mongo-myapp:
    image: de13/mongo-myapp
    stdin_open: true
    volumes:
    - foo:/data/db
    tty: true
    labels:
      io.rancher.container.pull_image: always
  myapp:
    image: de13/myapp
    stdin_open: true
    tty: true
    links:
    - mongo-myapp:mongodb
    labels:
      io.rancher.container.pull_image: always

volumes:
  foo:
    driver: rancher-ebs
    driver_opts:
      size: 10
      volumeType: gp2
      iops: 100
